---
resource_types:
- name: pcf-pool
  type: docker-image
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource

resources:
- name: cf-cli-release
  type: git
  source:
    uri: git@github.com:bosh-packages/cf-cli-release
    private_key: ((release-repo-github-key))
    branch: main

- name: cf-cli-release-final
  type: git
  source:
    uri: git@github.com:bosh-packages/cf-cli-release
    private_key: ((release-repo-github-key))
    branch: main

- name: gcp-env
  type: pcf-pool
  source:
    api_token: ((token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: cf-deployment

- name: v6-cli-binary-linux-64
  type: s3
  source:
    bucket: cf-cli-releases
    regexp: releases/v(.*)/cf-cli_(.*)_linux_x86-64.tgz
    region_name: us-west-1

- name: v7-cli-binary-linux-64
  type: s3
  source:
    bucket: v7-cf-cli-releases
    regexp: releases/v(.*)/cf7-cli_(.*)_linux_x86-64.tgz
    region_name: us-west-1

- name: v8-cli-binary-linux-64
  type: s3
  source:
    bucket: v8-cf-cli-releases
    regexp: releases/v(.*)/cf8-cli_(.*)_linux_x86-64.tgz
    region_name: us-west-1

- name: candidate-release
  type: s3
  source:
    bucket: cf-cli-bosh-release
    versioned_file: cf-cli-dev-release.tgz
    access_key_id: ((release-bucket-access-key-id))
    secret_access_key: ((release-bucket-secret-key))
    aws_role_arn: ((release-bucket-role-arn))
    region_name: us-west-1

- name: release-version
  type: semver
  source:
    access_key_id: ((release-bucket-access-key-id))
    secret_access_key: ((release-bucket-secret-key))
    aws_role_arn: ((release-bucket-role-arn))
    initial_version: 1.1.0
    bucket: cf-cli-bosh-release
    key: version
    region_name: us-west-1

- name: cf-cli-release-final-tarball
  type: s3
  source:
    bucket: cf-cli-bosh-release
    regexp: cf-cli-v(1\.\d+\.\d+)\.tgz
    access_key_id: {{release-bucket-access-key-id}}
    secret_access_key: {{release-bucket-secret-key}}
    aws_role_arn: ((release-bucket-role-arn))
    region_name: us-west-1

jobs:
  - name: update-cli
    plan:
      - in_parallel:
        - get: cf-cli-release
        - get: v6-cli-binary-linux-64
          trigger: true
        - get: v7-cli-binary-linux-64
          trigger: true
        - get: v8-cli-binary-linux-64
          trigger: true
      - task: bump-cli
        file: cf-cli-release/ci/tasks/bump-cli-release.yml
        input_mapping:
          v6-cli-binary: v6-cli-binary-linux-64
          v7-cli-binary: v7-cli-binary-linux-64
          v8-cli-binary: v8-cli-binary-linux-64
          cf-cli-release-input: cf-cli-release
        params:
          ACCESS_KEY_ID: ((release-bucket-access-key-id))
          SECRET_KEY: ((release-bucket-secret-key))
          AWS_ROLE_ARN: ((release-bucket-role-arn))
      - put: candidate-release
        params:
          file: "candidate-release-output/cf-cli-dev-release.tgz"
      - put: cf-cli-release
        params:
          repository: cf-cli-release-output
          rebase: true

  - name: run-tests
    serial: true
    plan:
    - in_parallel:
      - get: cf-cli-release
        passed: [update-cli]
        trigger: true
      - put: gcp-env
        params:
          action: claim
    - do:
      - task: run-tests
        file: cf-cli-release/ci/tasks/run-tests-toolsmiths.yml
    ensure:
      put: gcp-env
      params:
        action: unclaim
        env_file: gcp-env/metadata
      inputs:
      - gcp-env

  - name: finalize-release
    serial: true
    plan:
    - in_parallel:
      - get: cf-cli-release
        passed: [run-tests]
        trigger: true
      - get: release-version
        params:
          bump: minor
    - task: finalize-release
      file: cf-cli-release/ci/tasks/finalize-release.yml
      input_mapping:
        cf-cli-release-input: cf-cli-release
      params:
        ACCESS_KEY_ID: ((release-bucket-access-key-id))
        SECRET_KEY: ((release-bucket-secret-key))
        AWS_ROLE_ARN: ((release-bucket-role-arn))
    - put: release-version
      params:
        file: release-version/version
    - put: cf-cli-release-final
      params:
        repository: cf-cli-release-output
        rebase: true
        tag: release-version/version
    - put: cf-cli-release-final-tarball
      params:
        file: cf-cli-release-output/cf-cli-v1.*.tgz
